# version: '3.8'

# services:
#   voting_app:
#     image: prernaarora123/voting_app:latest
#     container_name: voting_app
#     restart: always
#     ports:
#       - "3000:3000"
#     environment:
#       - MONGODB_URL_LOCAL=mongodb://host.docker.internal:27017/voting
#       - PORT=3000
#       - JWT_SECRET=12345
services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  voting_app:
    build: .
    container_name: voting_app
    restart: always
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/voting
      - PORT=3000
      - JWT_SECRET=12345

volumes:
  mongo_data:
