version: '3.8'

services:
  voting_app:
    image: prernaarora123/voting_app:latest
    container_name: voting_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL_LOCAL=mongodb://host.docker.internal:27017/voting
      - PORT=3000
      - JWT_SECRET=12345
